CREATE DATABASE IF NOT EXISTS gymcore_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE gymcore_db;

CREATE TABLE IF NOT EXISTS alunos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    cpf VARCHAR(14) NOT NULL,
    plano VARCHAR(50) NOT NULL DEFAULT 'Mensal',
    status VARCHAR(20) NOT NULL DEFAULT 'Ativo',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);